apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: main-web-server
  name: main-web-server-rasp02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - env:
        - name: PREPROCESSOR_SERVICE_PORT
          value: '8000'
        - name: SERVICE_NAME
          value: edge-preprocessor
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: rdsea/od_web:2.0
        imagePullPolicy: Always
        name: web-server
        ports:
        - containerPort: 5000
      nodeSelector:
        kubernetes.io/hostname: aaltosea-rasp02-worker
