version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin_user
      MINIO_ROOT_PASSWORD: admin_pass
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9090"
