default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: /.*\.(py|yaml|json)$
      - id: end-of-file-fixer
        files: /.*\.(py|yaml|json)$
      - id: check-yaml
        exclude: ^templates/deployment_templates.yaml
        files: /.*\.yaml$
        args: [--allow-multiple-documents]
      - id: check-json
        files: /.*\.json$
      - id: pretty-format-json
        args: [--autofix]
        files: /.*\.json$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: /.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: /.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix]
        files: ^rohe/.*\.py$
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
