default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^core/.*\.(py|yaml|json)$
      - id: end-of-file-fixer
        files: ^core/.*\.(py|yaml|json)$
      - id: check-yaml
        files: ^core/.*\.yaml$
        args: [--allow-multiple-documents]
      - id: check-json
        files: ^core/.*\.json$
      - id: pretty-format-json
        args: [--autofix]
        files: ^core/.*\.json$

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        files: ^core/.*\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^core/.*\.py$

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: v0.2.0
  #   hooks:
  #   -   id: ruff
  #       args: [--fix]
  #       files: ^core/.*\.py$
