site_name: ROHE Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  # - social
  - search
  - awesome-pages

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition: null
  - codehilite: null
  - extra: null
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde: null
  - attr_list: null
  - md_in_html: null
  - mkdocs-click

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/rdsea

    - icon: /material/mailbox
      name: contact us
      link: https://rdsea.github.io/

copyright: |
  &copy; 2024 <a href="https://github.com/rdsea"  target="_blank" rel="noopener">Rdsea</a>
