[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "rohe"

[project]
name = "rohe"
version = "0.0.1"
description = "An orchestration framework for End-to-End Machine Learning Serving with Resource Optimization on Heterogeneous Edge"
authors = []
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
  "boto3==1.24.90",
  "botocore==1.27.90",
  "docker_py==1.10.6",
  "fastapi>=0.104.0",
  "Flask==2.2.3",
  "flask_restful==0.3.10",
  "gdown==4.7.1",
  "GitPython==3.1.40",
  "h5py==3.7.0",
  "Jinja2==3.1.2",
  "kubernetes==28.1.0",
  "matplotlib==3.6.2",
  "networkx==3.2",
  "numpy==1.23.5",
  "paho_mqtt==1.6.1",
  "pandas==1.4.3",
  "pika==1.3.2",
  "Pillow==10.1.0",
  "psutil==5.9.2",
  "pymongo==4.3.3",
  "python-dotenv==1.0.0",
  "PyYAML==6.0.1",
  "pyzmq==25.1.1",
  "qoa4ml==0.2.3",
  "quixstreams==0.5.7",
  # "ray==2.4.0",
  "scikit_learn==1.3.1",
  "tensorflow==2.10.0",
  "torch==2.1.0",
  "ultralytics==8.0.200",
  #NOTE: Flask doesn't specify this dependency well >=2.2.0, Werkzeug 3.0.0 will be installed and Flask 2.2.2 isn't made for Werkzeug 3.0.0 "Werkzeug==2.2.2",
  # Dev dependencies
  "pre-commit",
  "black",
  "isort",
  "devtools"
]

[project.urls]
Repository = "https://github.com/rdsea/ROHE"

[tool.isort]
profile = "black"

[tool.ruff.lint]
select = ["F", "C", "E", "R", "W", "N"]
ignore = [
  "E501", # Line too long
  "RET504", # Unnecessary assignment
  "RET505", # Unnecessary else after return
  "C901" # Too complex function
]

[tool.mypy]
python_version = "3.10"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
extra_checks = true
check_untyped_defs = true
ignore_missing_imports = true

