---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-od
  namespace: od-ray
  labels:
    app: main-client-od
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-od
  template:
    metadata:
      labels:
        app: client-od
    spec:
      containers:
        - name: client-od
          image: rdsea/od_client:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 8000
            - containerPort: 22
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NUM_THREAD
              value: 1
            - name: TIME_SLEEP
              value: -1
            - name: SERVICE_URL
              value: "http://0.0.0.0:8111/"

---
apiVersion: v1
kind: Service
metadata:
  namespace: od-ray
  name: client-od-service
spec:
  ports:
  - port: 80
    name: gcs 
    targetPort: 80
  - port: 8000
    name: serve
    targetPort: 8000
  - port: 22
    name: dashboard
    targetPort: 22
  selector:
    app: client-od