apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-inference-server-node_name
  labels:
    app: edge-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-inference-server
  template:
    metadata:
      labels:
        app: edge-inference-server
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: aaltosea-node_name-worker
      containers:
        - name: edge-inference
          image: rdsea/od_inf:2.0
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4002
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name