apiVersion: apps/v1
kind: Deployment
metadata:
  name: nii-ingestion-server-deployment
  labels:
    app: nii-ingestion-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nii-ingestion-server
  template:
    metadata:
      labels:
        app: nii-ingestion-server
    spec:
      hostAliases:
      - ip: "192.168.205.85"
        hostnames:
        - "host-machine"
      containers:
      - name: nii-ingestion-server
        image: vtn13042000/nii_ingestion_service_intel:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: minio_client_access_key
          value: "prJxdafe7L400AAXScc8"
        - name: minio_client_secret_key
          value: "2nC9WwmhZe8Ura1XaEo5My5YvXhKClgbq3SNNwV7"
        - name: HOST_SERVICE_URL_2
          value: "http://host-machine:5000"
        - name: MQTT_BROKER_URL
          value: "mqtt://host-machine:1883"
        volumeMounts:
        - name: ingestion-config-volume
          mountPath: /ingestion-server/app.json
          subPath: app.json
      volumes:
      - name: ingestion-config-volume
        hostPath:
          path: /home/vtn/aalto-internship/ROHE/examples/applications/NII/kube_deployment/dataIngestionService/configurations/ingestion_service.json
