---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-worker
  namespace: od-ray
  labels:
    app: main-ray-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-worker
  template:
    metadata:
      labels:
        app: ray-worker
    spec:
      containers:
        - name: ray-worker
          image: rdsea/od_ray_worker:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8111
            - containerPort: 8000
            - containerPort: 6379
            - containerPort: 8265
            - containerPort: 10001
            - containerPort: 52365
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # lifecycle:
          #   postStart:
          #     exec:
          #       command: ["ray", "start" , "--address", "ray-head-light-service:6379"]

---
apiVersion: v1
kind: Service
metadata:
  namespace: od-ray
  name: ray-worker-service
spec:
  ports:
  - port: 6379
    name: gcs 
    targetPort: 6379
  - port: 8000
    name: serve
    targetPort: 8000
  - port: 8265
    name: dashboard
    targetPort: 8265
  - port: 10001
    name: client
    targetPort: 10001
  - port: 52365
    name: default
    targetPort: 52365
  selector:
    app: ray-worker