apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - resnet50.yaml
  - efficientnet.yaml
  - mobilenet.yaml
  - vit.yaml
  - aggregator.yaml
