apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - redis.yaml
  - namespace.yaml
  - gateway.yaml
  - orchestrator.yaml
  - data-hub.yaml
  - preprocessor.yaml
  - resnet50.yaml
  - efficientnet.yaml
  - mobilenet.yaml
  - vit.yaml
  - aggregator.yaml
