---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-deployment
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
      - name: init-mosquitto
        image: busybox
        command: ['sh', '-c', 'cp /mosquitto/config/* /mosquitto/config-writable/']
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config
        - name: mosquitto-config-writable
          mountPath: /mosquitto/config-writable
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:latest
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 1883
        - containerPort: 9001
        volumeMounts:
        - name: mosquitto-config-writable
          mountPath: /mosquitto/config
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-config-writable
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
spec:
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: mqtt-web
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: NodePort  # Exposes the Service on each Node’s IP at a static port

