---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-web-server-node_name
  labels:
    app: main-web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: aaltosea-node_name-worker
      containers:
        - name: web-server
          image: rdsea/od_web:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PREPROCESSOR_SERVICE_PORT
              value: "8000"
            - name: SERVICE_NAME
              value: "edge-preprocessor"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name