apiVersion: apps/v1
kind: Deployment
metadata:
  name: bts_dataproc_service-Jetson_nano_02
  labels:
    app: bts_dataproc_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bts_dataproc_service
  template:
    metadata:
      labels:
        app: bts_dataproc_service
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: Jetson_nano_02
      containers:
        - name: bts_dataproc_service
          image: rdsea/bts_data_proc:2.0
          imagePullPolicy: "Always"
          ports: 
            - containerPort: 4002 
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: bts_dataproc_service-service
spec:
  ports: 
  - port: 4002 
    targetPort: 4002  
  - port: 4003 
    targetPort: 4003  
  selector:
    app: bts_dataproc_service