---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-preprocessor-node_name
  labels:
    app: edge-preprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-preprocessor
  template:
    metadata:
      labels:
        app: edge-preprocessor
    spec:
      nodeSelector:
        kubernetes.io/hostname: aaltosea-node_name-worker
      containers:
        - name: edge-preprocessor
          image: rdsea/od_proc:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: EDGE_INFERENCE_PREPROCESSOR_SERVICE_PORT
              value: "4002"
            - name: EDGE_INFERENCE_SERVICE_NAME
              value: "edge-inference-service"
            - name: CLOUD_INFERENCE_PREPROCESSOR_SERVICE_PORT
              value: "4001"
            - name: CLOUD_INFERENCE_SERVICE_NAME
              value: "cloud-inference-service"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name