apiVersion: apps/v1
kind: Deployment
metadata:
  name: nii-processing-server-deployment
  labels:
    app: nii-processing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nii-processing-server
  template:
    metadata:
      labels:
        app: nii-processing-server
    spec:
      containers:
      - name: nii-processing-server
        image: vtn13042000/nii_processing_service_intel:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        env:
        - name: minio_client_access_key
          value: "prJxdafe7L400AAXScc8"
        - name: minio_client_secret_key
          value: "2nC9WwmhZe8Ura1XaEo5My5YvXhKClgbq3SNNwV7"
        - name: HOST_SERVICE_URL_1
          value: "http://host-machine:9000"
        - name: HOST_SERVICE_URL_2
          value: "http://host-machine:5000"
        volumeMounts:
        - name: processing-config
          mountPath: /processing-service/examples/applications/NII/kube_deployment/dataProcessingService/configurations/processing_service.json
          subPath: processing_service.json
      volumes:
      - name: processing-config
        hostPath:
          path: processing_config.json
          type: File
