model_name: x3d_xs
test_run: false
version: 0
data_hub: http://0.0.0.0:5550
data_shape:
  - 1
  - 3
  - 4
  - 160
  - 160
model_config:
  XS:
    model_name: x3d_xs
    input_clip_length: 4
    input_crop_size: 160
    mean: [0.45, 0.45, 0.45]
    std: [0.225, 0.225, 0.225]

  S:
    model_name: x3d_s
    input_clip_length: 13
    input_crop_size: 160
    mean: [0.45, 0.45, 0.45]
    std: [0.225, 0.225, 0.225]

  M:
    model_name: x3d_m
    input_clip_length: 16
    input_crop_size: 224
    mean: [0.45, 0.45, 0.45]
    std: [0.225, 0.225, 0.225]

  L:
    model_name: x3d_l
    input_clip_length: 16
    input_crop_size: 312
    mean: [0.45, 0.45, 0.45]
    std: [0.225, 0.225, 0.225]
idx_to_label:
  "0": "Carrying_light"
  "1": "carrying"
  "2": "carrying_heavy"
  "3": "carrying_light"
  "4": "checking_time"
  "5": "closing"
  "6": "crouching"
  "7": "drinking"
  "8": "entering"
  "9": "exiting"
  "10": "fall"
  "11": "jumping"
  "12": "kicking"
  "13": "loitering"
  "14": "looking_around"
  "15": "opening"
  "16": "picking_up"
  "17": "pocket_in"
  "18": "pocket_out"
  "19": "pointing"
  "20": "pulling"
  "21": "pushing"
  "22": "running"
  "23": "setting_down"
  "24": "sitting"
  "25": "sitting_down"
  "26": "standing"
  "27": "standing_up"
  "28": "talking"
  "29": "talking_on_phone"
  "30": "throwing"
  "31": "transferring_object"
  "32": "using_pc"
  "33": "using_phone"
  "34": "walking"
  "35": "waving_hand"