services:
  resnet50:
    volumes:
      - ./simulation/:/app/simulation/:ro
      - ./sim_config/resnet50.yaml:/config/model.yaml:ro
      - ./sim_config/samples.yaml:/config/samples.yaml:ro
    environment:
      - MODEL_CONFIG=/config/model.yaml

  efficientnet:
    volumes:
      - ./simulation/:/app/simulation/:ro
      - ./sim_config/efficientnet.yaml:/config/model.yaml:ro
      - ./sim_config/samples.yaml:/config/samples.yaml:ro
    environment:
      - MODEL_CONFIG=/config/model.yaml

  mobilenet:
    volumes:
      - ./simulation/:/app/simulation/:ro
      - ./sim_config/mobilenet.yaml:/config/model.yaml:ro
      - ./sim_config/samples.yaml:/config/samples.yaml:ro
    environment:
      - MODEL_CONFIG=/config/model.yaml

  vit:
    volumes:
      - ./simulation/:/app/simulation/:ro
      - ./sim_config/vit.yaml:/config/model.yaml:ro
      - ./sim_config/samples.yaml:/config/samples.yaml:ro
    environment:
      - MODEL_CONFIG=/config/model.yaml
