version: '3'
services:
  nii_inference_server:
    image: vtn13042000/nii_ingestion_service_intel:1.0.0
    # ports:
    #   - "9000:9000"
    # volumes:
      # - /home/vtn/aalto-internship/test_model/VGG16/3/6/repair/model.json:/inference-server/data/architecture_file.json
      # - /home/vtn/aalto-internship/test_model/VGG16/3/6/repair/model.h5:/inference-server/data/weights_file.h5
    environment:
      minio_client_access_key: prJxdafe7L400AAXScc8
      minio_client_secret_key: 2nC9WwmhZe8Ura1XaEo5My5YvXhKClgbq3SNNwV7