version: '3'
services:
  nii_ingestion_server:
    image: vtn13042000/nii_ingestion_service_intel:1.0.0
    extra_hosts:
      - "host-machine:192.168.205.85"
    # ports:
    #   - "9000:9000"
    volumes:
      - /home/vtn/aalto-internship/ROHE/examples/applications/NII/kube_deployment/dataIngestionService/configurations/ingestion_service.json:/ingestion-server/app.json
      # - /home/vtn/aalto-internship/test_model/VGG16/3/6/repair/model.h5:/inference-server/data/weights_file.h5
    environment:
      minio_client_access_key: prJxdafe7L400AAXScc8
      minio_client_secret_key: 2nC9WwmhZe8Ura1XaEo5My5YvXhKClgbq3SNNwV7
      # HOST_SERVICE_URL_1: "http://host-machine:9000"  # Service on host machine at port 9000
      HOST_SERVICE_URL_2: "http://host-machine:5000"  # Service on host machine at port 5000
      MQTT_BROKER_URL: "mqtt://host-machine:1883"