client:
  appID: e7d3d243-a3b0-45f0-8a99-04a157d7f982
  application_name: dummy
  user_id: rohe_test
  instance_id: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  stage_id: rohe_test_stage
registration_url: http://localhost:5010/registration
