apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-client
  labels:
    app: kafka-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-client
  template:
    metadata:
      labels:
        app: kafka-client
    spec:
      containers:
      - name: kafka-client
        image: bitnami/kafka:latest
        command: ["sleep", "infinity"]
