apiVersion: v1
kind: Service
metadata:
  name: nii-inference-server-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090  
  selector:
    app: nii-inference
