collector:
  name: amqp_collector
  connector_type: AMQP
  config:
    end_point: localhost
    exchange_name: exchange_name
    exchange_type: topic
    in_queue: collector_1
    in_routing_key: in_routing_key
connector:
  name: amqp_connector
  connector_type: AMQP
  config:
    end_point: localhost
    exchange_name: exchange_name
    exchange_type: topic
    out_routing_key: out_routing_key
db_authentication:
  url: "localhost"
  prefix: "mongodb+srv://"
  username: "admin"
  password: "admin"
db_collection:
  collection: registration
  database: rohe_observation
agent_image: rdsea/rohe_stream_agent:1.0.0
