collector:
  amqp_collector:
    class: amqp
    conf:
      end_point: 195.148.22.62
      exchange_name: exchange_name
      exchange_type: topic
      in_queue: collector_1
      in_routing_key: in_routing_key
connector:
  amqp_connector:
    class: amqp
    conf:
      end_point: 195.148.22.62
      exchange_name: exchange_name
      exchange_type: topic
      out_routing_key: out_routing_key
database:
  collection: registration
  db_name: rohe_observation
  url: mongodb://195.148.22.62:27017/
false_rate: 3
logging_level: 2
output_folder: /results/
sample_rate: 50
timer: 10
window:
  interval:
    type: 2
    value: 3
  size:
    type: 2
    value: 100
agent_image: rdsea/rohe_stream_agent:1.0.0
