database:
  url: mongodb://localhost:27017/
  db_name: rohe_orchestration
  node_collection: node_collection
  service_collection: service_collection
timer: 10
output_folder: "/results/"
sample_rate: 50
false_rate: 3
service_queue:
  priority: 0
  queue_balance: 3
orchestrateConfig:
  name: Scoring Orchestration
  weights:
    cpu: 1
    memory: 1
  strategy: 1
