db_authentication:
  url: "localhost"
  prefix: "mongodb+srv://"
  username: "admin"
  password: "admin"
db_node_collection:
  collection: node_collection
  database: rohe_orchestration
db_service_collection:
  collection: service_collection
  database: rohe_orchestration
orchestration_interval: 10
output_folder: "/results/"
sample_rate: 50
false_rate: 3
service_queue_config:
  priority: 0
  queue_balance: 3
orchestrate_algorithm_config:
  algorithm: priority
  weights:
    cpu: 1
    memory: 1
  strategy: 1
