client:
  appID: ec28070e-9364-4983-8e3b-438a5c119eed
  appName: cctvs
  userID: rohe_test
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  stageID: rohe_test_stage
registration_url: http://localhost:5010/registration
