client:
  appID: ec28070e-9364-4983-8e3b-438a5c119eed
  application: cctvs
  client_id: rohe_test
  instance_name: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  stage_id: rohe_test_stage
registration_url: http://localhost:5010/registration
