client:
  appID: 9a58e1b7-6c23-46a2-8cf1-1cc9cb9df764
  application_name: cctvs
  instance_id: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  run_id: experiment2
  stage_id: rohe_test_stage
  user_id: aaltosea1
registration_url: http://localhost:5010/registration
