client:
  appID: 9a58e1b7-6c23-46a2-8cf1-1cc9cb9df764
  appName: cctvs
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  runID: experiment2
  stageID: rohe_test_stage
  userID: aaltosea1
registration_url: http://localhost:5010/registration
