qoa_config:
  client:
    userID: "aaltosea_client"
    instanceID: "Client01"
    stageID: "Client"
    method: "REST"
    appName: "test"
    role: "client"
  connector:
    amqp_connector:
      class: amqp
      conf:
        end_point: localhost
        exchange_name: nii_inference
        exchange_type: topic
        out_routing_key: nii.inference2
  registration_url: "http://0.0.0.0:5010/registration"

server_address: "http://localhost:30005/inference_service"
