version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    # restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /home/vtn/broker_config/mosquitto/config:/mosquitto/config
      - /home/vtn/broker_config/mosquitto/data:/mosquitto/data
      - /home/vtn/broker_config/mosquitto/log:/mosquitto/log
