apiVersion: apps/v1
kind: Deployment
metadata:
  name: object_detection_imgproc_service-Jetson_nano_04
  labels:
    app: object_detection_imgproc_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: object_detection_imgproc_service
  template:
    metadata:
      labels:
        app: object_detection_imgproc_service
    spec:
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: Jetson_nano_04
      containers:
        - name: object_detection_imgproc_service
          image: rdsea/od_proc:2.0
          imagePullPolicy: "Always"
          ports:
            - containerPort: 4002
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: object_detection_imgproc_service-service
spec:
  ports:
  - port: 4002
    targetPort: 4002
  - port: 4003
    targetPort: 4003
  selector:
    app: object_detection_imgproc_service
