version: '3'
services:
  nii_ingestion_server:
    image: vtn13042000/nii_ingestion_service_intel:1.0.0
    extra_hosts:
      - "host-machine:localhost"
    volumes:
      - ${ROHE_PATH}/examples/applications/object_classification/kube_deployment/dataIngestionService/ingestion_service.yaml:/ingestion-server/examples/applications/object_classification/kube_deployment/dataIngestionService/ingestion_service.yaml
    # environment:
    #   HOST_SERVICE_URL_2: "http://host-machine:5000"  # Service on host machine at port 5000
    #   MQTT_BROKER_URL: "mqtt://host-machine:1883"