version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_user
      MONGO_INITDB_ROOT_PASSWORD: admin_pass
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db
      
networks:
  mongo-network:
    driver: bridge
    
volumes:
  mongo-data:
