---
data_quality: class_label
metric:
  accuracy: max
  min_confidence: max
  avg_confidence: max
  percentage_confidence_over_50: max
  avg_confidence_correct_prediction: max
  avg_confidence_incorrect_prediction: max
  min_response_time: max
  max_response_time: max
  avg_response_time: max