
external_services:
  minio_storage:
    endpoint_url: http://128.214.254.126:9000   #fixed endpoint
    access_key: admin_user
    secret_key: admin_pass
    bucket_name: nii-application-unprocessed-image

  service_registry:
    consul_config:
      url: http://195.148.22.62:8500
    service:
      image_info:   # dynamic endpoint
        type: one
        tags: ['nii_case']
    