missRateOfClass1and6:
  variables:
  - name: wrong_sub
    conditions:
    - field: label_class
      operator: eq
      value: 1
    - field: predicted_class
      operator: eq
      value: 6
    - field: accuracy
      operator: eq
      value: 0
    aggregation: count
  - name: total
    conditions:
    - field: label_class
      operator: eq
      value: 1
    aggregation: count
  overall_aggregation: "{wrong_sub} / {total}"
missRateOfClass1:
  variables:
  - name: wrong_main
    conditions:
    - field: label_class
      operator: eq
      value: 1
    - field: accuracy
      operator: eq
      value: 0
    aggregation: count
  - name: total
    conditions:
    - field: label_class
      operator: eq
      value: 1
    aggregation: count
  overall_aggregation: "{wrong_main} / {total}"
generalAccuracy:
  variables:
  - name: correctInference
    conditions:
    - field: accuracy
      operator: eq
      value: 1
    aggregation: count
  - name: total
    conditions: []
    aggregation: count
  overall_aggregation: "{correctInference} / {total}"

confidenceOnClass1:
  variables:
  - name: avgConfidence
    field: confidence
    conditions:
    - field: label_class
      operator: eq
      value: 1
    aggregation: avg
  overall_aggregation: "{avgConfidence}"
