apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
spec:
  selector:
    app: mqtt-broker
  ports:
    - name: mqtt  
      protocol: TCP
      port: 1883
      nodePort: 31083 
    - name: websockets 
      protocol: TCP
      port: 9001
      nodePort: 31001 
  type: NodePort
