apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: datapreprocessing
  type: LoadBalancer
  ports:
  - port: 5000
    name: defaultport
    protocol: TCP
    targetPort: 5000