client:
  appID: 4a2e0a02-d7b6-45f7-85ce-efdce1f55375
  appName: sdn
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  runID: experiment1
  stageID: rohe_test_stage
  userID: aaltosea1
registration_url: http://localhost:5010/registration
