client:
  appID: 861f6325-37dd-4f8e-8d04-7278694856de
  appName: sdn
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  runID: experiment1
  stageID: rohe_test_stage
  userID: aaltosea1
registration_url: http://localhost:5010/registration
