client:
  appID: 29e5bac5-dcd0-4d9f-be92-2d672033d10c
  appName: sdn
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  runID: experiment1
  stageID: rohe_test_stage
  userID: aaltosea1
registration_url: http://localhost:5010/registration
