client:
  appID: 4a2e0a02-d7b6-45f7-85ce-efdce1f55375
  application_name: sdn
  instance_id: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  run_id: experiment1
  stage_id: rohe_test_stage
  user_id: aaltosea1
registration_url: http://localhost:5010/registration
