client:
  appID: c8b925ce-7e97-4cec-ac05-ed92642852e0
  appName: sdn
  instanceID: rohe_test_isntance
  method: rohe_test_method
  role: rohe_test_role
  runID: experiment1
  stageID: rohe_test_stage
  userID: aaltosea1
registration_url: http://localhost:5010/registration
